# Generated by Django 3.1.5 on 2021-02-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, upload_to='', verbose_name='ファイルの追加'),
        ),
    ]
